### ISSUE TITLE
tweetBot crash when no tweets are present

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#143]
tweetBot crashes wenever there are not enough tweets to have top *n* mentions / hashtags.

````bash
/[...]/controller/tweetBot.js:30
                        topMentions = '@' + msg.entities.topMentions[0].key + ', @' + msg.entities.topMentions[1].key + ' and @' + msg.entities.topMentions[2].key
                                                                        ^
TypeError: Cannot read property 'key' of undefined
    at process.<anonymous> (/[...]/controller/tweetBot.js:30:52)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
````

To be fixed by disabling the tweetBot whenever there is not enough content.

**Comment by mef** [comment]
implemented in v4.0.0
