### ISSUE TITLE
feedback form broken

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/twitto_be#72]
the feedback form fails all the time.

Upon submission, the result is:

> Server error. Please try again later.

No more details on the client side.

On the server, the following can be read in the `log-fpm-fcgi` logs (`app/storage/logs/` folder) (not sure if related):

````
[2015-10-26 23:29:39] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /media/dbStorage/websites/twitto.be/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429
Stack trace:
#0 /media/dbStorage/websites/twitto.be/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /media/dbStorage/websites/twitto.be/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /media/dbStorage/websites/twitto.be/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /media/dbStorage/websites/twitto.be/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(506): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /media/dbStorage/websites/twitto.be/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
````

**Comment by mef** [comment]
some logging should be added [here](https://github.com/Mango-information-systems/twitto_be/blob/6af3920c378c280d7bd5e2cbafff8fafe71084a8/site/app/controllers/HomeController.php#L64).

@11digitlabs, would you have an idea about how to solve this problem?
